const $=id=>document.getElementById(id);
let token=localStorage.getItem('ai_nav_token');
let map, street, satellite, routeLayer, userMarker, destinationMarker, watchId, lastWeatherPoint=null, lastWeatherDistance=0, currentRoute=null, recording=false, mediaRecorder=null, audioChunks=[];
const layerKey='ai_nav_map_layer';
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500)}
function authHeaders(){return token?{Authorization:`Bearer ${token}`}:{}}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...authHeaders()};const r=await fetch(url,opt);if(r.status===401){logout();throw new Error('Требуется вход')}if(!r.ok){let x=await r.text();try{x=JSON.parse(x).detail||x}catch{};throw new Error(x)}return r.json()}
function initMap(){map=L.map('map',{zoomControl:false}).setView([31.77,35.21],7);L.control.zoom({position:'bottomright'}).addTo(map);street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});(localStorage.getItem(layerKey)==='satellite'?satellite:street).addTo(map);document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));map.on('click',e=>setDestination(e.latlng.lat,e.latlng.lng))}
function setLayer(x){map.eachLayer(l=>{if(l===street||l===satellite)map.removeLayer(l)});(x==='satellite'?satellite:street).addTo(map);localStorage.setItem(layerKey,x);document.querySelectorAll('[data-layer]').forEach(b=>b.classList.toggle('active',b.dataset.layer===x))}
async function setDestination(lat,lon,label){if(destinationMarker)map.removeLayer(destinationMarker);destinationMarker=L.marker([lat,lon]).addTo(map);$('destination').value=label||`${lat.toFixed(5)}, ${lon.toFixed(5)}`;await buildRoute(lat,lon,label)}
async function buildRoute(lat,lon,label){if(!navigator.geolocation){toast('Геолокация недоступна');return}try{const p=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:10000}));const d=await api('/api/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start_lat:p.coords.latitude,start_lon:p.coords.longitude,end_lat:lat,end_lon:lon,destination_label:label})});currentRoute=d;drawRoute(d);$('routePanel').hidden=false;$('distance').textContent=formatDistance(d.distance_m);$('eta').textContent=formatDuration(d.duration_s);$('routeDestination').textContent=d.place||label||''}catch(e){toast(e.message)}}
function drawRoute(d){if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(d.geometry,{style:{weight:6,opacity:.9}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[60,160]})}
function formatDistance(m){return m<1000?`${m} м`:`${(m/1000).toFixed(1)} км`}function formatDuration(s){let m=Math.round(s/60);return m<60?`~${m} мин`:`~${Math.floor(m/60)} ч ${m%60} мин`}
$('searchBtn').onclick=async()=>{try{const q=$('destination').value.trim();if(!q)return;const x=await api('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q})});setDestination(x.lat,x.lon,x.name)}catch(e){toast(e.message)}};
$('destination').addEventListener('keydown',e=>{if(e.key==='Enter')$('searchBtn').click()});
function updateAuth(){const ok=!!token;$('authBox').hidden=ok;$('userBox').hidden=!ok;if(ok)api('/api/me').then(x=>$('userEmail').textContent=x.email).catch(()=>{});}
$('loginBtn').onclick=async()=>auth('/api/login');$('registerBtn').onclick=async()=>auth('/api/register');async function auth(url){try{const x=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});const d=await x.json();if(!x.ok)throw new Error(d.detail||'Ошибка');token=d.token;localStorage.setItem('ai_nav_token',token);updateAuth();toast('Готово')}catch(e){toast(e.message)}}
function logout(){token=null;localStorage.removeItem('ai_nav_token');updateAuth()}$('logoutBtn').onclick=logout;
$('startBtn').onclick=async()=>{if(!currentRoute)return;try{const p=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true}));const x=await api('/api/route/start-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat:p.coords.latitude,lon:p.coords.longitude})});if(x.image){$('sceneImg').src=x.image;$('scenePlace').textContent=x.place;$('generatedImage').hidden=false}startTracking()}catch(e){toast(e.message)}};
function startTracking(){if(watchId)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;if(!userMarker)userMarker=L.circleMarker([lat,lon],{radius:8}).addTo(map);else userMarker.setLatLng([lat,lon]);if(!lastWeatherPoint||distanceMeters(lastWeatherPoint.lat,lastWeatherPoint.lon,lat,lon)-lastWeatherDistance>=200){lastWeatherDistance=lastWeatherPoint?lastWeatherDistance+distanceMeters(lastWeatherPoint.lat,lastWeatherPoint.lon,lat,lon):0;lastWeatherPoint={lat,lon};loadWeather(lat,lon)}},e=>toast('Не удалось получить геопозицию'),{enableHighAccuracy:true,maximumAge:3000});}
function distanceMeters(a,b,c,d){const R=6371000,rad=x=>x*Math.PI/180;const x=rad(c-a),y=rad(d-b);const h=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
async function loadWeather(lat,lon){try{const w=await api('/api/weather',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat,lon})});if(!w)return;const icon=w.weather?.[0]?.icon;$('weatherCard').hidden=false;$('weatherCard').innerHTML=`<b>${Math.round(w.main.temp)}°C</b> ${w.weather?.[0]?.description||''}<div class="muted">${w.name||''} · 💧 ${w.main.humidity}% · 💨 ${w.wind?.speed??0} м/с</div>`}catch(e){console.warn(e)}}
$('weatherCard').onclick=()=>$('weatherCard').classList.toggle('expanded');
$('closeScene').onclick=()=>$('generatedImage').hidden=true;
async function startVoice(){if(recording){stopVoice();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);audioChunks=[];mediaRecorder.ondataavailable=e=>e.data.size&&audioChunks.push(e.data);mediaRecorder.onstop=sendVoice;mediaRecorder.start();recording=true;$('orb').parentElement.classList.add('listening');$('orbStatus').textContent='Слушаю… нажмите ещё раз для отправки'}catch(e){toast('Разрешите доступ к микрофону')}}
function stopVoice(){if(mediaRecorder&&recording){mediaRecorder.stop();mediaRecorder.stream.getTracks().forEach(t=>t.stop());recording=false;$('orb').parentElement.classList.remove('listening');$('orbStatus').textContent='Обрабатываю…'}}
async function sendVoice(){try{const blob=new Blob(audioChunks,{type:'audio/webm'});const fd=new FormData();fd.append('file',blob,'voice.webm');const x=await api('/api/voice/transcribe',{method:'POST',body:fd});if(!x.transcript){toast('Не удалось распознать речь');return}const p=userMarker?.getLatLng();const c=await api('/api/voice/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript:x.transcript,current_lat:p?.lat,current_lon:p?.lng})});$('destination').value=c.text;const s=await api('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:c.text})});await setDestination(s.lat,s.lon,s.name)}catch(e){toast(e.message)}finally{$('orbStatus').textContent='Нажмите, чтобы говорить'}}
$('orb').onclick=startVoice;
$('historyBtn').onclick=async()=>{try{const list=await api('/api/history');$('historyList').innerHTML=list.length?list.map(x=>`<div class="history-item"><b>${x.destination?.label||'Маршрут'}</b><span>${formatDistance(x.distance_m)} · ${formatDuration(x.duration_s)} · ${new Date(x.created_at).toLocaleString()}</span></div>`).join(''):'<div class="muted">История пуста</div>';$('historyModal').hidden=false}catch(e){toast(e.message)}};$('closeHistory').onclick=()=>$('historyModal').hidden=true;
initMap();updateAuth();
